# Generated by Django 3.0.5 on 2020-05-23 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0002_auto_20200523_1330")]

    operations = [
        migrations.RemoveField(model_name="user", name="background_pic"),
        migrations.RemoveField(model_name="user", name="data_of_birth"),
        migrations.RemoveField(model_name="user", name="profile_pic"),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.CharField(blank=True, max_length=250, null=True)),
                ("location", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "profile_pic",
                    models.ImageField(blank=True, upload_to="users/%y/%m/%d/"),
                ),
                (
                    "background_pic",
                    models.ImageField(blank=True, upload_to="users/%y/%m/%d/"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
