# Generated by Django 3.0.5 on 2020-05-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200524_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='n_books_upladed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
