# Generated by Django 3.0.5 on 2020-06-21 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200524_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='n_books_upladed',
        ),
    ]
