# Generated by Django 3.0.5 on 2020-05-02 17:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=100)),
                ('pages', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('cover_pg', models.URLField()),
                ('download_link', models.URLField()),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('genre', models.CharField(max_length=250)),
                ('summary', models.TextField()),
            ],
        ),
    ]
