# Generated by Django 3.0.5 on 2020-08-01 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("users", "0009_auto_20200719_1131")]

    operations = [
        migrations.RemoveField(model_name="user", name="background_pic"),
        migrations.RemoveField(model_name="user", name="profile_pic"),
    ]
