# Generated by Django 3.0.5 on 2020-05-10 15:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("author", models.CharField(max_length=100)),
                ("pages", models.IntegerField(null=True)),
                ("rank", models.IntegerField(null=True)),
                ("cover_pg", models.URLField(null=True)),
                ("download_link", models.URLField()),
                ("publish", models.DateTimeField(default=django.utils.timezone.now)),
                ("genre", models.CharField(max_length=250)),
                ("summary", models.TextField(null=True)),
                ("file_name", models.CharField(max_length=250)),
            ],
        )
    ]
