# Generated by Django 3.0.14 on 2021-05-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("form", models.CharField(max_length=20)),
                (
                    "confidence",
                    models.CharField(
                        choices=[("G", "Good"), ("A", "Average"), ("B", "Bad")],
                        max_length=1,
                    ),
                ),
                ("learning_started", models.DateTimeField(auto_now_add=True)),
                ("last_revised", models.DateTimeField(auto_now=True)),
            ],
        )
    ]
