# Generated by Django 3.2 on 2021-05-22 06:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("form", models.CharField(max_length=20)),
                (
                    "confidence",
                    models.CharField(
                        choices=[("G", "Good"), ("A", "Average"), ("B", "Bad")],
                        max_length=1,
                    ),
                ),
                ("learning_started", models.DateTimeField(auto_now_add=True)),
                ("last_revised", models.DateTimeField(auto_now=True)),
                ("user", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["form"]},
        )
    ]
