# Generated by Django 3.2 on 2021-05-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_alter_word_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='word',
            name='last_revised',
        ),
        migrations.AddField(
            model_name='word',
            name='easiness',
            field=models.FloatField(null=True, verbose_name='Easiness'),
        ),
        migrations.AddField(
            model_name='word',
            name='interval',
            field=models.IntegerField(null=True, verbose_name='Next review interval'),
        ),
        migrations.AddField(
            model_name='word',
            name='last_review',
            field=models.DateTimeField(auto_now=True, verbose_name='Last review'),
        ),
        migrations.AddField(
            model_name='word',
            name='next_review',
            field=models.DateField(null=True, verbose_name='Next review'),
        ),
        migrations.AddField(
            model_name='word',
            name='repetitions',
            field=models.IntegerField(null=True, verbose_name='Successful review streak'),
        ),
        migrations.AlterField(
            model_name='word',
            name='form',
            field=models.CharField(max_length=20, verbose_name='Word form'),
        ),
        migrations.AlterField(
            model_name='word',
            name='learning_started',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Started learning'),
        ),
    ]
