# Generated by Django 3.0.14 on 2021-05-16 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("words", "0002_word_user")]

    operations = [
        migrations.AlterModelOptions(name="word", options={"ordering": ["form"]})
    ]
